# Generated by Django 5.2.8 on 2025-11-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password_hash', models.TextField()),
            ],
            options={
                'db_table': 'admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookCSE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_uuid', models.UUIDField()),
                ('book_name', models.TextField()),
                ('authors', models.TextField(null=True)),
                ('genre', models.TextField(null=True)),
                ('branch', models.CharField(max_length=64)),
                ('pdf_data', models.BinaryField()),
                ('uploaded_by', models.CharField(max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'books_cse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookEEE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_uuid', models.UUIDField()),
                ('book_name', models.TextField()),
                ('authors', models.TextField(null=True)),
                ('genre', models.TextField(null=True)),
                ('branch', models.CharField(max_length=64)),
                ('pdf_data', models.BinaryField()),
                ('uploaded_by', models.CharField(max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'books_eee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookView',
            fields=[
                ('local_id', models.IntegerField()),
                ('book_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('book_name', models.TextField()),
                ('authors', models.TextField(null=True)),
                ('genre', models.TextField(null=True)),
                ('branch', models.CharField(max_length=64)),
                ('pdf_data', models.BinaryField()),
                ('uploaded_by', models.CharField(max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField()),
                ('fragment', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('institute_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('institute_mail', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=32)),
                ('password_hash', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
